applications: 
  - name: bot-dev
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/poliNetworkOrg/polinetwork-cd
      targetRevision: HEAD
      path: bot-dev
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: bot-dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
    info:
    - name: url
      value: https://argoproj.github.io/
  - name: bot-prod
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/poliNetworkOrg/polinetwork-cd
      targetRevision: HEAD
      path: bot-prod
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: bot-prod
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
    info:
    - name: url
      value: https://argoproj.github.io/
  - name: bot-mat
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/poliNetworkOrg/polinetwork-cd
      targetRevision: HEAD
      path: bot-mat
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: bot-mat
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
    info:
    - name: url
      value: https://argoproj.github.io/
  - name: mariadb
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/poliNetworkOrg/polinetwork-cd
      targetRevision: HEAD
      path: mariadb
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: mariadb
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
    info:
    - name: url
      value: https://argoproj.github.io/
  - name: k8s-dashboard
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/poliNetworkOrg/polinetwork-cd
      targetRevision: HEAD
      path: dashboard
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: kubernetes-dashboard
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    info:
    - name: url
      value: https://argoproj.github.io/
  - name: app-dev
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/poliNetworkOrg/polinetwork-cd
      targetRevision: HEAD
      path: app-dev
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: app-dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
    info:
    - name: url
      value: https://argoproj.github.io/
  - name: polimi-tutorapp
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/poliNetworkOrg/polinetwork-ext-cd
      targetRevision: HEAD
      path: tutorapp-prod
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: tutorapp-prod
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    info:
    - name: url
      value: https://argoproj.github.io/